// Generated by gencpp from file controllers/motion.msg
// DO NOT EDIT!


#ifndef CONTROLLERS_MESSAGE_MOTION_H
#define CONTROLLERS_MESSAGE_MOTION_H

#include <ros/service_traits.h>


#include <controllers/motionRequest.h>
#include <controllers/motionResponse.h>


namespace controllers
{

struct motion
{

typedef motionRequest Request;
typedef motionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct motion
} // namespace controllers


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::controllers::motion > {
  static const char* value()
  {
    return "5f07416156f9cd98c81988e24b4d6bda";
  }

  static const char* value(const ::controllers::motion&) { return value(); }
};

template<>
struct DataType< ::controllers::motion > {
  static const char* value()
  {
    return "controllers/motion";
  }

  static const char* value(const ::controllers::motion&) { return value(); }
};


// service_traits::MD5Sum< ::controllers::motionRequest> should match
// service_traits::MD5Sum< ::controllers::motion >
template<>
struct MD5Sum< ::controllers::motionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::controllers::motion >::value();
  }
  static const char* value(const ::controllers::motionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::controllers::motionRequest> should match
// service_traits::DataType< ::controllers::motion >
template<>
struct DataType< ::controllers::motionRequest>
{
  static const char* value()
  {
    return DataType< ::controllers::motion >::value();
  }
  static const char* value(const ::controllers::motionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::controllers::motionResponse> should match
// service_traits::MD5Sum< ::controllers::motion >
template<>
struct MD5Sum< ::controllers::motionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::controllers::motion >::value();
  }
  static const char* value(const ::controllers::motionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::controllers::motionResponse> should match
// service_traits::DataType< ::controllers::motion >
template<>
struct DataType< ::controllers::motionResponse>
{
  static const char* value()
  {
    return DataType< ::controllers::motion >::value();
  }
  static const char* value(const ::controllers::motionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTROLLERS_MESSAGE_MOTION_H
