// Generated by gencpp from file controllers/motionResult.msg
// DO NOT EDIT!


#ifndef CONTROLLERS_MESSAGE_MOTIONRESULT_H
#define CONTROLLERS_MESSAGE_MOTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controllers
{
template <class ContainerAllocator>
struct motionResult_
{
  typedef motionResult_<ContainerAllocator> Type;

  motionResult_()
    : succeeded(false)  {
    }
  motionResult_(const ContainerAllocator& _alloc)
    : succeeded(false)  {
  (void)_alloc;
    }



   typedef uint8_t _succeeded_type;
  _succeeded_type succeeded;





  typedef boost::shared_ptr< ::controllers::motionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controllers::motionResult_<ContainerAllocator> const> ConstPtr;

}; // struct motionResult_

typedef ::controllers::motionResult_<std::allocator<void> > motionResult;

typedef boost::shared_ptr< ::controllers::motionResult > motionResultPtr;
typedef boost::shared_ptr< ::controllers::motionResult const> motionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controllers::motionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controllers::motionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::controllers::motionResult_<ContainerAllocator1> & lhs, const ::controllers::motionResult_<ContainerAllocator2> & rhs)
{
  return lhs.succeeded == rhs.succeeded;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::controllers::motionResult_<ContainerAllocator1> & lhs, const ::controllers::motionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace controllers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::controllers::motionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controllers::motionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controllers::motionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controllers::motionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controllers::motionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controllers::motionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controllers::motionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95e696a0d10686913abb262e0b4cbbcf";
  }

  static const char* value(const ::controllers::motionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95e696a0d1068691ULL;
  static const uint64_t static_value2 = 0x3abb262e0b4cbbcfULL;
};

template<class ContainerAllocator>
struct DataType< ::controllers::motionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controllers/motionResult";
  }

  static const char* value(const ::controllers::motionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controllers::motionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#Define the result\n"
"bool succeeded	\n"
;
  }

  static const char* value(const ::controllers::motionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controllers::motionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.succeeded);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controllers::motionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controllers::motionResult_<ContainerAllocator>& v)
  {
    s << indent << "succeeded: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.succeeded);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLERS_MESSAGE_MOTIONRESULT_H
