// Generated by gencpp from file pioneer2dx_controllers/motionFeedback.msg
// DO NOT EDIT!


#ifndef PIONEER2DX_CONTROLLERS_MESSAGE_MOTIONFEEDBACK_H
#define PIONEER2DX_CONTROLLERS_MESSAGE_MOTIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace pioneer2dx_controllers
{
template <class ContainerAllocator>
struct motionFeedback_
{
  typedef motionFeedback_<ContainerAllocator> Type;

  motionFeedback_()
    : actual_position()  {
    }
  motionFeedback_(const ContainerAllocator& _alloc)
    : actual_position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _actual_position_type;
  _actual_position_type actual_position;





  typedef boost::shared_ptr< ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct motionFeedback_

typedef ::pioneer2dx_controllers::motionFeedback_<std::allocator<void> > motionFeedback;

typedef boost::shared_ptr< ::pioneer2dx_controllers::motionFeedback > motionFeedbackPtr;
typedef boost::shared_ptr< ::pioneer2dx_controllers::motionFeedback const> motionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator1> & lhs, const ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.actual_position == rhs.actual_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator1> & lhs, const ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pioneer2dx_controllers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e54b00c7d8e976a3c9bd4ca7cb24983";
  }

  static const char* value(const ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e54b00c7d8e976aULL;
  static const uint64_t static_value2 = 0x3c9bd4ca7cb24983ULL;
};

template<class ContainerAllocator>
struct DataType< ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pioneer2dx_controllers/motionFeedback";
  }

  static const char* value(const ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#Define a feedback message\n"
"geometry_msgs/Twist actual_position\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actual_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pioneer2dx_controllers::motionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "actual_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.actual_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIONEER2DX_CONTROLLERS_MESSAGE_MOTIONFEEDBACK_H
