(cl:defpackage quadrotor_controllers-msg
  (:use )
  (:export
   "<MOTIONACTION>"
   "MOTIONACTION"
   "<MOTIONACTIONFEEDBACK>"
   "MOTIONACTIONFEEDBACK"
   "<MOTIONACTIONGOAL>"
   "MOTIONACTIONGOAL"
   "<MOTIONACTIONRESULT>"
   "MOTIONACTIONRESULT"
   "<MOTIONFEEDBACK>"
   "MOTIONFEEDBACK"
   "<MOTIONGOAL>"
   "MOTIONGOAL"
   "<MOTIONRESULT>"
   "MOTIONRESULT"
  ))

