; Auto-generated. Do not edit!


(cl:in-package quadrotor_controllers-msg)


;//! \htmlinclude motionFeedback.msg.html

(cl:defclass <motionFeedback> (roslisp-msg-protocol:ros-message)
  ((actual_position
    :reader actual_position
    :initarg :actual_position
    :type geometry_msgs-msg:Twist
    :initform (cl:make-instance 'geometry_msgs-msg:Twist)))
)

(cl:defclass motionFeedback (<motionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <motionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'motionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name quadrotor_controllers-msg:<motionFeedback> is deprecated: use quadrotor_controllers-msg:motionFeedback instead.")))

(cl:ensure-generic-function 'actual_position-val :lambda-list '(m))
(cl:defmethod actual_position-val ((m <motionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader quadrotor_controllers-msg:actual_position-val is deprecated.  Use quadrotor_controllers-msg:actual_position instead.")
  (actual_position m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <motionFeedback>) ostream)
  "Serializes a message object of type '<motionFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'actual_position) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <motionFeedback>) istream)
  "Deserializes a message object of type '<motionFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'actual_position) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<motionFeedback>)))
  "Returns string type for a message object of type '<motionFeedback>"
  "quadrotor_controllers/motionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'motionFeedback)))
  "Returns string type for a message object of type 'motionFeedback"
  "quadrotor_controllers/motionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<motionFeedback>)))
  "Returns md5sum for a message object of type '<motionFeedback>"
  "9e54b00c7d8e976a3c9bd4ca7cb24983")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'motionFeedback)))
  "Returns md5sum for a message object of type 'motionFeedback"
  "9e54b00c7d8e976a3c9bd4ca7cb24983")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<motionFeedback>)))
  "Returns full string definition for message of type '<motionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define a feedback message~%geometry_msgs/Twist actual_position~%~%~%~%================================================================================~%MSG: geometry_msgs/Twist~%# This expresses velocity in free space broken into its linear and angular parts.~%Vector3  linear~%Vector3  angular~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%# It is only meant to represent a direction. Therefore, it does not~%# make sense to apply a translation to it (e.g., when applying a ~%# generic rigid transformation to a Vector3, tf2 will only apply the~%# rotation). If you want your data to be translatable too, use the~%# geometry_msgs/Point message instead.~%~%float64 x~%float64 y~%float64 z~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'motionFeedback)))
  "Returns full string definition for message of type 'motionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define a feedback message~%geometry_msgs/Twist actual_position~%~%~%~%================================================================================~%MSG: geometry_msgs/Twist~%# This expresses velocity in free space broken into its linear and angular parts.~%Vector3  linear~%Vector3  angular~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%# It is only meant to represent a direction. Therefore, it does not~%# make sense to apply a translation to it (e.g., when applying a ~%# generic rigid transformation to a Vector3, tf2 will only apply the~%# rotation). If you want your data to be translatable too, use the~%# geometry_msgs/Point message instead.~%~%float64 x~%float64 y~%float64 z~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <motionFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'actual_position))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <motionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'motionFeedback
    (cl:cons ':actual_position (actual_position msg))
))
