; Auto-generated. Do not edit!


(cl:in-package controllers-msg)


;//! \htmlinclude motionResult.msg.html

(cl:defclass <motionResult> (roslisp-msg-protocol:ros-message)
  ((succeeded
    :reader succeeded
    :initarg :succeeded
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass motionResult (<motionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <motionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'motionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name controllers-msg:<motionResult> is deprecated: use controllers-msg:motionResult instead.")))

(cl:ensure-generic-function 'succeeded-val :lambda-list '(m))
(cl:defmethod succeeded-val ((m <motionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader controllers-msg:succeeded-val is deprecated.  Use controllers-msg:succeeded instead.")
  (succeeded m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <motionResult>) ostream)
  "Serializes a message object of type '<motionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'succeeded) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <motionResult>) istream)
  "Deserializes a message object of type '<motionResult>"
    (cl:setf (cl:slot-value msg 'succeeded) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<motionResult>)))
  "Returns string type for a message object of type '<motionResult>"
  "controllers/motionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'motionResult)))
  "Returns string type for a message object of type 'motionResult"
  "controllers/motionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<motionResult>)))
  "Returns md5sum for a message object of type '<motionResult>"
  "95e696a0d10686913abb262e0b4cbbcf")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'motionResult)))
  "Returns md5sum for a message object of type 'motionResult"
  "95e696a0d10686913abb262e0b4cbbcf")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<motionResult>)))
  "Returns full string definition for message of type '<motionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define the result~%bool succeeded	~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'motionResult)))
  "Returns full string definition for message of type 'motionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Define the result~%bool succeeded	~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <motionResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <motionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'motionResult
    (cl:cons ':succeeded (succeeded msg))
))
