// Auto-generated. Do not edit!

// (in-package pioneer3at_controllers.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class motionResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.succeeded = null;
    }
    else {
      if (initObj.hasOwnProperty('succeeded')) {
        this.succeeded = initObj.succeeded
      }
      else {
        this.succeeded = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type motionResult
    // Serialize message field [succeeded]
    bufferOffset = _serializer.bool(obj.succeeded, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type motionResult
    let len;
    let data = new motionResult(null);
    // Deserialize message field [succeeded]
    data.succeeded = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pioneer3at_controllers/motionResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '95e696a0d10686913abb262e0b4cbbcf';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #Define the result
    bool succeeded	
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new motionResult(null);
    if (msg.succeeded !== undefined) {
      resolved.succeeded = msg.succeeded;
    }
    else {
      resolved.succeeded = false
    }

    return resolved;
    }
};

module.exports = motionResult;
