// Generated by gencpp from file pioneer3at_controllers/motionResult.msg
// DO NOT EDIT!


#ifndef PIONEER3AT_CONTROLLERS_MESSAGE_MOTIONRESULT_H
#define PIONEER3AT_CONTROLLERS_MESSAGE_MOTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pioneer3at_controllers
{
template <class ContainerAllocator>
struct motionResult_
{
  typedef motionResult_<ContainerAllocator> Type;

  motionResult_()
    : succeeded(false)  {
    }
  motionResult_(const ContainerAllocator& _alloc)
    : succeeded(false)  {
  (void)_alloc;
    }



   typedef uint8_t _succeeded_type;
  _succeeded_type succeeded;





  typedef boost::shared_ptr< ::pioneer3at_controllers::motionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pioneer3at_controllers::motionResult_<ContainerAllocator> const> ConstPtr;

}; // struct motionResult_

typedef ::pioneer3at_controllers::motionResult_<std::allocator<void> > motionResult;

typedef boost::shared_ptr< ::pioneer3at_controllers::motionResult > motionResultPtr;
typedef boost::shared_ptr< ::pioneer3at_controllers::motionResult const> motionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pioneer3at_controllers::motionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pioneer3at_controllers::motionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pioneer3at_controllers::motionResult_<ContainerAllocator1> & lhs, const ::pioneer3at_controllers::motionResult_<ContainerAllocator2> & rhs)
{
  return lhs.succeeded == rhs.succeeded;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pioneer3at_controllers::motionResult_<ContainerAllocator1> & lhs, const ::pioneer3at_controllers::motionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pioneer3at_controllers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pioneer3at_controllers::motionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pioneer3at_controllers::motionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pioneer3at_controllers::motionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pioneer3at_controllers::motionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pioneer3at_controllers::motionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pioneer3at_controllers::motionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pioneer3at_controllers::motionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95e696a0d10686913abb262e0b4cbbcf";
  }

  static const char* value(const ::pioneer3at_controllers::motionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95e696a0d1068691ULL;
  static const uint64_t static_value2 = 0x3abb262e0b4cbbcfULL;
};

template<class ContainerAllocator>
struct DataType< ::pioneer3at_controllers::motionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pioneer3at_controllers/motionResult";
  }

  static const char* value(const ::pioneer3at_controllers::motionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pioneer3at_controllers::motionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#Define the result\n"
"bool succeeded	\n"
;
  }

  static const char* value(const ::pioneer3at_controllers::motionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pioneer3at_controllers::motionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.succeeded);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pioneer3at_controllers::motionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pioneer3at_controllers::motionResult_<ContainerAllocator>& v)
  {
    s << indent << "succeeded: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.succeeded);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PIONEER3AT_CONTROLLERS_MESSAGE_MOTIONRESULT_H
